with open('database', 'w') as f:
    f.write("statistics:0:start:\n점수:score:\nDO NOT EDIT THIS FILE\nstatistics:0:end:")
with open('database_username', 'w') as f:
    f.write("username")
print("Scoreboard initialized")